import re
import textwrap
from dataclasses import dataclass, field
from typing import NamedTuple

import torch
import torch.nn.functional as F

from game import pick_words, score_guess

MAX_ATTEMPTS = 6

SYSTEM_PROMPT = textwrap.dedent("""\
    You are playing Wordle. Rules:
    - Guess a 5-letter English word each turn.
    - For each letter you receive feedback:
        correct  - right letter, right position
        present  - right letter, wrong position
        absent   - letter not in the word
    - Reply with exactly your next guess, no other text.
""")


class RunResult(NamedTuple):
    tokens: list[int]
    mask: list[int]  # 1 = generated by the agent, 0 = system prompt / game feedback
    # Sampling logprobs from the rollout policy, aligned with `tokens`.
    # Entries for non-generated positions (mask == 0) are 0.0 placeholders.
    sample_logprobs: list[float]
    score: int


@dataclass
class _RolloutState:
    rollout_idx: int
    word: str
    messages: list[dict[str, str]]
    tokens: list[int] = field(default_factory=list)
    mask: list[int] = field(default_factory=list)
    sample_logprobs: list[float] = field(default_factory=list)
    total_correct: int = 0
    total_present: int = 0
    score: int = 0
    done: bool = False


def _format_feedback(guess: str, scores: list[str]) -> str:
    return " ".join(f"{g.upper()}:{s}" for g, s in zip(guess, scores))


def _extract_guess(text: str) -> str | None:
    m = re.search(r"(?i)guess[:\s]+([a-zA-Z]{5})\b", text)
    if m:
        return m.group(1).lower()
    words = re.findall(r"\b[a-zA-Z]{5}\b", text)
    return words[-1].lower() if words else None


def _render_prompt(tokenizer, msgs: list[dict[str, str]]) -> tuple[str, list[int]]:
    prompt_text = tokenizer.apply_chat_template(
        msgs,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=True,
    )
    prompt_ids = tokenizer.encode(prompt_text, add_special_tokens=False)
    return prompt_text, prompt_ids


def _extend_with_context_delta(state: _RolloutState, prompt_ids: list[int]) -> None:
    if not state.tokens:
        state.tokens = list(prompt_ids)
        state.mask = [0] * len(prompt_ids)
        state.sample_logprobs = [0.0] * len(prompt_ids)
        return

    prefix_len = 0
    max_prefix_len = min(len(state.tokens), len(prompt_ids))
    while prefix_len < max_prefix_len and state.tokens[prefix_len] == prompt_ids[prefix_len]:
        prefix_len += 1

    if prefix_len < len(state.tokens):
        return

    added = prompt_ids[prefix_len:]
    if added:
        state.tokens.extend(added)
        state.mask.extend([0] * len(added))
        state.sample_logprobs.extend([0.0] * len(added))


def _batched_generate(
    model,
    tokenizer,
    prompt_ids_list: list[list[int]],
    *,
    max_new_tokens: int,
) -> list[tuple[list[int], list[float], str]]:
    """Generate one turn for each prompt, left-padded into a single batch."""
    if not prompt_ids_list:
        return []

    device = next(model.parameters()).device
    pad_id = tokenizer.pad_token_id
    if pad_id is None:
        pad_id = tokenizer.eos_token_id
    eos_id = tokenizer.eos_token_id

    prompt_tensors = [torch.tensor(ids, dtype=torch.long) for ids in prompt_ids_list]
    max_prompt_len = max(t.size(0) for t in prompt_tensors)
    batch_size = len(prompt_tensors)

    input_ids = torch.full((batch_size, max_prompt_len), pad_id, dtype=torch.long, device=device)
    attention_mask = torch.zeros((batch_size, max_prompt_len), dtype=torch.long, device=device)
    for i, prompt in enumerate(prompt_tensors):
        seq_len = prompt.size(0)
        input_ids[i, max_prompt_len - seq_len:] = prompt
        attention_mask[i, max_prompt_len - seq_len:] = 1

    prev_use_cache = model.config.use_cache
    model.config.use_cache = True
    try:
        outputs = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=1.0,
            pad_token_id=pad_id,
            return_dict_in_generate=True,
            output_scores=True,
        )
    finally:
        model.config.use_cache = prev_use_cache

    sequences = outputs.sequences
    scores = outputs.scores or ()

    results: list[tuple[list[int], list[float], str]] = []
    for i in range(batch_size):
        gen_ids = sequences[i, max_prompt_len:].tolist()

        trimmed_ids: list[int] = []
        gen_logprobs: list[float] = []
        for step, tok_id in enumerate(gen_ids):
            if eos_id is not None and tok_id == eos_id:
                break
            trimmed_ids.append(tok_id)
            if step < len(scores):
                step_logits = scores[step][i]
                log_probs = F.log_softmax(step_logits.float(), dim=-1)
                gen_logprobs.append(float(log_probs[tok_id].item()))
            else:
                gen_logprobs.append(0.0)

        response = tokenizer.decode(trimmed_ids, skip_special_tokens=False)
        results.append((trimmed_ids, gen_logprobs, response))

    return results


def run_rollouts(
    model,
    tokenizer,
    num_rollouts: int,
    targets: list[str] | None = None,
    max_tokens: int = 512,
) -> list[RunResult]:
    if num_rollouts <= 0:
        return []
    if targets is not None and len(targets) != num_rollouts:
        raise ValueError("targets must be None or have length equal to num_rollouts")

    if targets is not None:
        words = list(targets)
    else:
        words = pick_words(num_rollouts)

    states: list[_RolloutState] = []
    for i, word in enumerate(words):
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": "Make your first guess."},
        ]
        _, prompt_ids = _render_prompt(tokenizer, messages)
        states.append(
            _RolloutState(
                rollout_idx=i,
                word=word,
                messages=messages,
                tokens=list(prompt_ids),
                mask=[0] * len(prompt_ids),
                sample_logprobs=[0.0] * len(prompt_ids),
            )
        )

    for attempt_num in range(1, MAX_ATTEMPTS + 1):
        active_states = [s for s in states if not s.done]
        if not active_states:
            break

        prompt_ids_list: list[list[int]] = []
        for state in active_states:
            _, prompt_ids = _render_prompt(tokenizer, state.messages)
            _extend_with_context_delta(state, prompt_ids)
            prompt_ids_list.append(list(state.tokens))

        batch_outputs = _batched_generate(
            model,
            tokenizer,
            prompt_ids_list,
            max_new_tokens=max_tokens,
        )

        for state, (generated_ids, gen_logprobs, response) in zip(active_states, batch_outputs):
            state.tokens.extend(generated_ids)
            state.mask.extend([1] * len(generated_ids))
            state.sample_logprobs.extend(gen_logprobs)

            think_match = re.search(r"<think>.*?</think>(.*)", response, re.DOTALL)
            answer_text = (think_match.group(1) if think_match else response).strip()

            guess = _extract_guess(answer_text)
            if guess is None:
                print(
                    f"Rollout {state.rollout_idx + 1} attempt {attempt_num}: "
                    "could not parse a 5-letter guess. Run failed."
                )
                state.score = 0
                state.done = True
                continue

            try:
                scores = score_guess(state.word, guess)
            except ValueError as exc:
                print(
                    f"Rollout {state.rollout_idx + 1} attempt {attempt_num}: "
                    f"invalid guess '{guess}' ({exc}). Run failed."
                )
                state.score = 0
                state.done = True
                continue

            state.total_correct += sum(1 for s in scores if s == "correct")
            state.total_present += sum(1 for s in scores if s == "present")

            feedback = _format_feedback(guess, scores)
            print(f"Rollout {state.rollout_idx + 1} attempt {attempt_num}: {guess.upper()} -> {feedback}")

            state.score = 2 * state.total_correct + state.total_present
            if all(s == "correct" for s in scores):
                unused = MAX_ATTEMPTS - attempt_num
                state.score += 12 * unused
                state.done = True
                print(
                    f"Rollout {state.rollout_idx + 1} solved in {attempt_num} attempt(s). "
                    f"Word: {state.word.upper()}. Score: {state.score}"
                )
                continue

            if attempt_num == MAX_ATTEMPTS:
                state.done = True
                print(
                    f"Rollout {state.rollout_idx + 1} out of attempts. "
                    f"Word: {state.word.upper()}. Score: {state.score}"
                )
                continue

            state.messages.append({"role": "assistant", "content": response.strip()})
            state.messages.append({"role": "user", "content": f"Feedback: {feedback}\nMake your next guess."})

    return [
        RunResult(
            tokens=s.tokens,
            mask=s.mask,
            sample_logprobs=s.sample_logprobs,
            score=s.score,
        )
        for s in states
    ]


def run_agent(model, tokenizer, target: str | None = None) -> RunResult:
    targets = [target] if target is not None else None
    return run_rollouts(model, tokenizer, num_rollouts=1, targets=targets)[0]
