import re
import textwrap
from typing import NamedTuple

import torch

from game import pick_word, score_guess

MAX_ATTEMPTS = 6

SYSTEM_PROMPT = textwrap.dedent("""\
    You are playing Wordle. Rules:
    - Guess a 5-letter English word each turn.
    - For each letter you receive feedback:
        correct  - right letter, right position
        present  - right letter, wrong position
        absent   - letter not in the word
    - Reply with: GUESS: <word>
""")


class RunResult(NamedTuple):
    tokens: list[int]
    mask: list[int]  # 1 = generated by the agent, 0 = system prompt / game feedback
    score: int


def _format_feedback(guess: str, scores: list[str]) -> str:
    return " ".join(f"{g.upper()}:{s}" for g, s in zip(guess, scores))


def _extract_guess(text: str) -> str | None:
    m = re.search(r"(?i)guess[:\s]+([a-zA-Z]{5})\b", text)
    if m:
        return m.group(1).lower()
    words = re.findall(r"\b[a-zA-Z]{5}\b", text)
    return words[-1].lower() if words else None


def run_agent(model, tokenizer, target: str | None = None) -> RunResult:
    word = target if target is not None else pick_word()

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": "Make your first guess."},
    ]

    def _render(msgs) -> list[int]:
        text = tokenizer.apply_chat_template(
            msgs,
            tokenize=False,
            add_generation_prompt=True,
            enable_thinking=True,
        )
        return tokenizer.encode(text, add_special_tokens=False)

    tokens: list[int] = _render(messages)
    mask: list[int] = [0] * len(tokens)

    total_correct = 0
    total_present = 0

    for attempt_num in range(1, MAX_ATTEMPTS + 1):
        input_ids = torch.tensor([tokens], device=model.device)
        with torch.no_grad():
            output_ids = model.generate(
                input_ids,
                max_new_tokens=512,
                do_sample=True,
                pad_token_id=tokenizer.eos_token_id,
            )
        new_generated = output_ids[0][len(tokens):].tolist()
        tokens.extend(new_generated)
        mask.extend([1] * len(new_generated))

        response = tokenizer.decode(new_generated, skip_special_tokens=False)
        think_match = re.search(r"<think>.*?</think>(.*)", response, re.DOTALL)
        answer_text = (think_match.group(1) if think_match else response).strip()

        guess = _extract_guess(answer_text)
        if guess is None:
            print(f"Attempt {attempt_num}: could not parse a 5-letter guess. Run failed.")
            return RunResult(tokens, mask, 0)

        try:
            scores = score_guess(word, guess)
        except ValueError as exc:
            print(f"Attempt {attempt_num}: invalid guess '{guess}' ({exc}). Run failed.")
            return RunResult(tokens, mask, 0)

        total_correct += sum(1 for s in scores if s == "correct")
        total_present += sum(1 for s in scores if s == "present")

        feedback = _format_feedback(guess, scores)
        print(f"Attempt {attempt_num}: {guess.upper()} -> {feedback}")

        if all(s == "correct" for s in scores):
            unused = MAX_ATTEMPTS - attempt_num
            score = 12 * (unused + 1)
            print(f"Solved in {attempt_num} attempt(s). Word: {word.upper()}. Score: {score}")
            return RunResult(tokens, mask, score)

        if attempt_num == MAX_ATTEMPTS:
            break

        # Append the feedback turn; use the tokenizer to render it correctly.
        messages.append({"role": "assistant", "content": answer_text})
        messages.append({"role": "user", "content": f"Feedback: {feedback}\nMake your next guess."})
        new_context = _render(messages)
        added = new_context[len(tokens):]
        tokens.extend(added)
        mask.extend([0] * len(added))

    score = 2 * total_correct + total_present
    print(f"Out of attempts. Word: {word.upper()}. Score: {score}")
    return RunResult(tokens, mask, score)
